
services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "1337:1337"
    volumes:
      - "./content:/app/content:ro,Z"
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    volumes:
      - "./content/downloads:/app/content/downloads:Z"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["tail","-f","/dev/null"]