services:
  follower:
    build:
      context: .
      dockerfile: follower/Dockerfile
    ports:
      - "5001:5000"

  leader:
    build:
      context: .
      dockerfile: leader/Dockerfile
    environment:
      - FOLLOWER_URL=http://follower:5000
    depends_on:
      - follower
    ports:
      - "5000:5000"
