
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: lab2_server
    ports:
      - "8088:8088"
    restart: unless-stopped
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: lab2_client
    depends_on:
      - server
    command: ["python","load_server.py","--url","http://server:8088/"]